name: 'Deploy to Digital Ocean'

on:
  push:
    branches:
      - 'main'
      - 'feature/*'

jobs:
  terraform:
    environment: terraform-backend
    name: terraform
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      id-token: write
      contents: read

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}

      - name: Configuring AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-duration-seconds: 1800
          role-session-name: WorkSmarterBlogDeploy
          aws-region: us-east-1

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config "bucket=${{ secrets.BACKEND_S3 }}" \
            -backend-config "region=us-east-1" \
            -backend-config "dynamo_table=${{ secrets.BACKEND_DYNAMO }} \
            -backend-config "key=work-smarter-blog-server/terraform.state"
        working-directory: terraform/blog-server

      - name: Create Workspace
        run: terraform workspace new dev || terraform workspace select dev
        continue-on-error: true
        working-directory: terraform/blog-server

      - name: Terraform Plan
        run: terraform plan -var-file do_real.tfvars -out plan
        working-directory: terraform/blog-server

      - name: Terraform Apply
        run: terraform apply plan
        working-directory: terraform/blog-server