name: 'Scan feature branch'

on:
  push:
    branches:
      - 'feature/*'

jobs:
  Tfscan:
    name: tfscan
    needs: check_user
    runs-on: self-hosted
    timeout-minutes: 30
    container:
      image: aquasec/tfsec:latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name:
        run: tree .
      - name: TFsec Scan
        run: tfsec