name: 'Scan feature branch'

on:
  push:
    branches:
      - 'feature/*'

jobs:
  Tfscan:
    name: tfscan
#    runs-on: self-hosted
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: aquasec/tfsec:latest
    steps:
      - uses: actions/checkout@v2
      - name: check
        run: ls