name: 'Scan feature branch'

on:
  push:
    branches:
      - 'feature/*'

jobs:
  Tfscan:
    name: tfscan
    runs-on: self-hosted
    timeout-minutes: 30
    container:
      image: ubuntu:latest
    steps:
      - name: check dir
        run: pwd