name: 'Scan feature branch'

on:
  push:
    branches:
      - 'feature/*'

jobs:
  Tfscan:
    name: tfscan
    runs-on: self-hosted
    timeout-minutes: 30
    container:
      image: aquasec/tfsec:latest

    steps:
      - name: Check Dir
        run: tree .
      - name: TFsec Scan
        run: tfsec