name: 'Scan feature branch'

on:
  push:
    branches:
      - 'feature/*'

jobs:
  Tfscan:
    name: tfscan
    runs-on: self-hosted
    timeout-minutes: 30
#    container:
#      image: python:latest
    steps:
      - uses: actions/checkout@v2
      - name: TFsec Scan
        uses: aquasecurity/tfsec-action@v1.0.3
      - name: check
        run: ls -alh && pwd