name: 'Scan feature branch'

on:
  push:
    branches:
      - 'feature/*'

jobs:
  Tfscan:
    name: tfscan
    runs-on: self-hosted
    timeout-minutes: 30
    container:
      image: aquasec/tfsec:latest
    steps:
#      - name: TFsec Scan
#        run: tfsec
      - name: check hostname
        run: echo "hostname: $(hostname)"
      - name: check dir
        run: ls -alh && pwd